services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: hass-dev
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components
      - ../dist:/config/www/room-card-minimalist
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
